title: Tuğrulcan Elmas
position: Ph.D. Student
affiliation: EPFL
email: tugrulcan.elmas (at) epfl.ch
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=0oyamTsAAAAJ&hl=en&oi=ao
github_link: https://github.com/tugrulz
linkedin: https://www.linkedin.com/in/tugrulcanelmas/
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
