title: Tuğrulcan Elmas
position: Postdoctoral Scholar
affiliation: IU
email: telmas (at) iu.edu
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=0oyamTsAAAAJ&hl=en&oi=ao
github_link: https://github.com/tugrulz
linkedin: https://www.linkedin.com/in/tugrulcanelmas/
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: Wellcome to Tugrulcan's personal space
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
instagram: https://www.instagram.com/tugrulcanelmas
twitter: https://www.twitter.com/tugrulcanelmas